query ClassSearch($classSearchArgs: ClassSearchArgs!) {
  classSearch(classSearchArgs: $classSearchArgs) {
    id
    classNumber
    maxSelection
    minSelection
    requiredSelection
    SGSlabel
  }
}
