query ClassByNumber($festivalClassNumber: String!) {
	festivalClassByNumber(festivalClassNumber: $festivalClassNumber) {

		id
		class_number
		max_selection
		min_selection
		required_selection
		SGS_label
		price
		category {
			id
			name
			description
			required_composer
		}
		level {
			id
			name
			description
		}
		subdiscipline {
			id
			name
			description
			discipline {
				id
				name
			}
		}
		trophies {
			id
			name
			description
		}
	}
}
