query ClassSearch($classSearchArgs: ClassSearchArgs!) {
	classSearch(classSearchArgs: $classSearchArgs) {
		id
		classNumber
		maxSelection
		minSelection
		requiredSelection
		SGSlabel
		price
		subdiscipline {
			name
		}
		level {
			name
		}
		category {
			name
		}
		trophies {
			id
			name
			description
		}
	}
}
