query CommunityInfo($registrationId: ID!) {
	registration(id: $registrationId) {
		communities {
			id
			name
			groupSize
			chaperones
			wheelchairs
			earliestTime
			latestTime
			unavailable
			conflictPerformers
		}
	}
}
