query GroupInfo($registrationId: ID!) {
	registration(id: $registrationId) {
		groups {
			id
			age
			groupType
			instruments
			name
			numberOfPerformers
		}
		teacher {
			id
			prefix
			firstName
			lastName
			apartment
			streetNumber
			streetName
			city
			province
			postalCode
			phone
			email
		}
		performers {
			id
			firstName
			lastName
			age
			apartment
			streetNumber
			streetName
			city
			province
			postalCode
			phone
			email
			instrument
			level
			otherClasses
		}
	}
}
