query PerformerLoad($registrationId: ID!) {
	registration(id: $registrationId) {
		performers {
			id
			firstName
			lastName
			age
			apartment
			streetNumber
			streetName
			city
			province
			postalCode
			phone
			email
			instrument
			level
		}
	}
}
