query RegisteredClasses($registrationId: Int!) {
  registration(id: $registrationId) {
    registeredClasses {
      category
      class_number
      discipline
      id
      level
      number_of_selections
      price
      subdiscipline
      school_groupID
      selections {
        composer
        duration
        id
        larger_work
        movement
        title
      }
    }
  }
}
