query SchoolGroupInfo($registrationId: Int!) {
  registration(id: $registrationId) {
    school {
      schoolGroups {
        id
        name
        group_size
        chaperones
        wheelchairs
        earliest_time
        latest_time
        unavailable
        conflict_performers
      }
    }
  }
}
