query SchoolInfo($registrationId: Int!) {
	registration(id: $registrationId) {
		school {
			id
			name
			division
			street_number
			street_name
			city
			province
			postal_code
			phone
		}
	}
}
