query SubdisciplinesByType($disciplineId: ID, $sgSlabel: SGSlabel!) {
	subdisciplinesByType(disciplineID: $disciplineId, SGSlabel: $sgSlabel) {
		id
		name
		description
		maxPerformers
		minPerformers
		price
		SGSlabel
	}
}
