query TeacherLoad($registrationId: Int!) {
	registration(id: $registrationId) {
		teacher {
			id
			prefix
			first_name
			last_name
			apartment
			street_number
			street_name
			city
			province
			postal_code
			phone
			email
		}
	}
}
